#lang racket/base

(require "test-0n1.rkt"
         "test-0n1n.rkt"
         "test-01-equal.rkt"
         "test-baby-json.rkt"
         "test-baby-json-hider.rkt"
         "test-curly-quantifier.rkt"
         "test-cutter.rkt"
         "test-empty-symbol.rkt"
         "test-errors.rkt"
         "test-flatten.rkt"
         "test-hide-and-splice.rkt"
         "test-lexer.rkt"
         "test-nested-repeats.rkt"
         "test-old-token.rkt"
         "test-parser.rkt"
         "test-quotation-marks-and-backslashes.rkt"
         "test-simple-arithmetic-grammar.rkt"
         "test-simple-line-drawing.rkt"
         "test-start-and-atok.rkt"
         "test-top-level-cut.rkt"
         "test-weird-grammar.rkt"
         "test-whitespace.rkt"
         "test-wordy.rkt"
         (submod brag/codegen/satisfaction test))
